# Generated by Django 4.1.7 on 2023-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aww', '0003_catalog_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='status',
            field=models.CharField(blank=True, choices=[('WW', 'Kompiluje się z ostrzeżeniami'), ('NW', 'Kompiluje się bez ostrzeżeń'), ('NC', 'Nie kompiluje się')], max_length=2, null=True),
        ),
    ]
