# Generated by Django 4.1.7 on 2023-05-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aww', '0005_remove_filesection_end_character_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
