# Generated by Django 4.1.7 on 2023-05-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aww', '0006_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='delated_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='delated_at',
            new_name='deleted_at',
        ),
    ]
