# Generated by Django 4.1.7 on 2023-05-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aww', '0004_alter_filesection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesection',
            name='end_character',
        ),
        migrations.RemoveField(
            model_name='filesection',
            name='start_character',
        ),
    ]
